# Generated by Django 3.0.6 on 2020-07-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspost',
            name='items',
            field=models.CharField(choices=[(' Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Home Improvement', 'Home_Improvement'), ('Scraps', 'Scraps'), ('Clothing', 'Clothing')], max_length=20),
        ),
    ]
